### ISSUE TITLE
Failed when intsalling with --only=prod flag

### ISSUE THREAD

**Issue by dicky1126277766238** [chatdaddy/service-auth-client#1]
Hello, I have a project running `npm install --only=prod` on production.
However, this package will lead to a failure because it does not install packages in `devDependencies` and the `prepare` hook will run `tsc` and it need those packages at the same time.

**Comment by adiwajshing** [comment]
@dicky1126277766238 have you tried using yarn with `yarn add git+https://github.com/chatdaddy/service-auth-client`?

**Comment by dicky1126277766238** [comment]
Oh never mind. I cleaned up `node_modules` and it works again. Also works with `yarn install --production=true`.

**Comment by dicky1126277766238** [comment]
Just encountered it again. I'vs tried removing `node_module` + `package-lock.json` and `npm cache clean`, but it still gives this error. Here is the log.

> ERR! code 2
> npm ERR! git dep preparation failed
> npm ERR! command /home/ubuntu/.nvm/versions/node/v14.15.4/bin/node /home/ubuntu/.nvm/versions/node/v14.15.4/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/ubuntu/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
> npm ERR! > @chatdaddy/service-auth-client@0.1.0 prepare
> npm ERR! > tsc
> npm ERR!
> npm ERR! src/index.ts(2,29): error TS2307: Cannot find module 'jsonwebtoken' or its corresponding type declarations.
> npm ERR! src/index.ts(3,28): error TS2307: Cannot find module 'crypto' or its corresponding type declarations.
> npm ERR! src/index.ts(34,15): error TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
> npm ERR! src/index.ts(42,14): error TS2580: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
> npm ERR! npm WARN using --force Recommended protections disabled.
> npm ERR! npm ERR! code 2
> npm ERR! npm ERR! path /home/ubuntu/.npm/_cacache/tmp/git-clone-71ccd778
> npm ERR! npm ERR! command failed
> npm ERR! npm ERR! command sh -c tsc
> npm ERR!
> npm ERR! npm ERR! A complete log of this run can be found in:
> npm ERR! npm ERR!     /home/ubuntu/.npm/_logs/2021-08-16T10_32_00_307Z-debug.log
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/ubuntu/.npm/_logs/2021-08-16T10_32_02_553Z-debug.log


Maybe it can be reproduced by installing with an old package-lock.json. Here is the log when I tried to install before I clean everything.

> npm WARN old lockfile
> npm WARN old lockfile The package-lock.json file was created with an old version of npm,
> npm WARN old lockfile so supplemental metadata must be fetched from the registry.
> npm WARN old lockfile
> npm WARN old lockfile This is a one-time fix-up, please be patient...
> npm WARN old lockfile
> npm WARN old lockfile Error: git dep preparation failed
> npm WARN old lockfile     at ChildProcess.<anonymous> (/home/ubuntu/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
> npm WARN old lockfile     at ChildProcess.emit (events.js:315:20)
> npm WARN old lockfile     at maybeClose (internal/child_process.js:1048:16)
> npm WARN old lockfile     at Socket.<anonymous> (internal/child_process.js:439:11)
> npm WARN old lockfile     at Socket.emit (events.js:315:20)
> npm WARN old lockfile     at Pipe.<anonymous> (net.js:673:12)
> npm WARN old lockfile  Could not fetch metadata for @chatdaddy/service-auth-client@git+ssh://git@github.com/chatdaddy/service-auth-client.git#83d13858d66acd5d80929bcb0326b43ca455e414 Error: git dep preparation failed
> npm WARN old lockfile     at ChildProcess.<anonymous> (/home/ubuntu/.nvm/versions/node/v14.15.4/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
> npm WARN old lockfile     at ChildProcess.emit (events.js:315:20)
> npm WARN old lockfile     at maybeClose (internal/child_process.js:1048:16)
> npm WARN old lockfile     at Socket.<anonymous> (internal/child_process.js:439:11)
> npm WARN old lockfile     at Socket.emit (events.js:315:20)
> npm WARN old lockfile     at Pipe.<anonymous> (net.js:673:12) {
> npm WARN old lockfile   cmd: '/home/ubuntu/.nvm/versions/node/v14.15.4/bin/node',
> npm WARN old lockfile   args: [
> npm WARN old lockfile     '/home/ubuntu/.nvm/versions/node/v14.15.4/lib/node_modules/npm/bin/npm-cli.js',
> npm WARN old lockfile     'install',
> npm WARN old lockfile     '--force',
> npm WARN old lockfile     '--cache=/home/ubuntu/.npm',
> npm WARN old lockfile     '--prefer-offline=false',
> npm WARN old lockfile     '--prefer-online=false',
> npm WARN old lockfile     '--offline=false',
> npm WARN old lockfile     '--no-progress',
> npm WARN old lockfile     '--no-save',
> npm WARN old lockfile     '--no-audit'
> npm WARN old lockfile   ],
> npm WARN old lockfile   code: 2,
> npm WARN old lockfile   signal: null,
> npm WARN old lockfile   stdout: '\n' +
> npm WARN old lockfile     '> @chatdaddy/service-auth-client@0.1.0 prepare\n' +
> npm WARN old lockfile     '> tsc\n' +
> npm WARN old lockfile     '\n' +
> npm WARN old lockfile     "src/index.ts(2,29): error TS2307: Cannot find module 'jsonwebtoken' or its corresponding type declarations.\n" +
> npm WARN old lockfile     "src/index.ts(3,28): error TS2307: Cannot find module 'crypto' or its corresponding type declarations.\n" +
> npm WARN old lockfile     "src/index.ts(34,15): error TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.\n" +
> npm WARN old lockfile     "src/index.ts(42,14): error TS2580: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.\n",
> npm WARN old lockfile   stderr: 'npm WARN using --force Recommended protections disabled.\n' +
> npm WARN old lockfile     'npm ERR! code 2\n' +
> npm WARN old lockfile     'npm ERR! path /home/ubuntu/.npm/_cacache/tmp/git-clone-3049f9db\n' +
> npm WARN old lockfile     'npm ERR! command failed\n' +
> npm WARN old lockfile     'npm ERR! command sh -c tsc\n' +
> npm WARN old lockfile     '\n' +
> npm WARN old lockfile     'npm ERR! A complete log of this run can be found in:\n' +
> npm WARN old lockfile     'npm ERR!     /home/ubuntu/.npm/_logs/2021-08-16T09_37_27_887Z-debug.log\n'
> npm WARN old lockfile }
> npm ERR! code 2
> npm ERR! git dep preparation failed
> npm ERR! command /home/ubuntu/.nvm/versions/node/v14.15.4/bin/node /home/ubuntu/.nvm/versions/node/v14.15.4/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/ubuntu/.npm --prefer-offline=false --prefer-online=false --of
> fline=false --no-progress --no-save --no-audit
> npm ERR! > @chatdaddy/service-auth-client@0.1.0 prepare
> npm ERR! > tsc
> npm ERR!
> npm ERR! src/index.ts(2,29): error TS2307: Cannot find module 'jsonwebtoken' or its corresponding type declarations.
> npm ERR! src/index.ts(3,28): error TS2307: Cannot find module 'crypto' or its corresponding type declarations.
> npm ERR! src/index.ts(34,15): error TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
> npm ERR! src/index.ts(42,14): error TS2580: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
> npm ERR! npm WARN using --force Recommended protections disabled.
> npm ERR! npm ERR! code 2
> npm ERR! npm ERR! path /home/ubuntu/.npm/_cacache/tmp/git-clone-a8358102
> npm ERR! npm ERR! command failed
> npm ERR! npm ERR! command sh -c tsc

**Comment by dicky1126277766238** [comment]
Also about yarn. I found that it does not work even in my local machine.
It won't complain while installing, but the typescript source will not be built and so the package cannot be used.

it can be reproduced by a minimum setup

package.json
```
{
  "name": "test-package",
  "dependencies": {
    "@chatdaddy/service-auth-client": "github:chatdaddy/service-auth-client"
  }
}
```
index.js
```
const chatdaddy = require('@chatdaddy/service-auth-client')
```

run `yarn install --production=true` and then `node index.js`, it will throw

> internal/modules/cjs/loader.js:311
>       throw err;
>       ^
> 
> Error: Cannot find module 'path\to\chatdaddy-package\node_modules\@chatdaddy\service-auth-client\lib\index'. Please verify that the package.json has a valid "main" entry
>     at tryPackage (internal/modules/cjs/loader.js:303:19)
>     at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
>     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
>     at Module.require (internal/modules/cjs/loader.js:952:19)
>     at require (internal/modules/cjs/helpers.js:88:18)
>     at Object.<anonymous> (path\to\chatdaddy-package\index.js:1:19)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>     at Module.load (internal/modules/cjs/loader.js:928:32) {
>   code: 'MODULE_NOT_FOUND',
>   path: 'path\\to\\chatdaddy-package\\node_modules\\@chatdaddy\\service-auth-client\\package.json',
>   requestPath: '@chatdaddy/service-auth-client'
> }
